### ISSUE TITLE
Unexpected results when merging

### ISSUE THREAD

**Issue by malcolmredheron** [Wortex17/jsod#1]
I'm having trouble explaining some of the results that I get from this library when doing three-way merges.

For example:

```
var jsod = require("jsod");

var a = ["0", "1", "2", "3"];
var b = ["0", "1", "2", "3"];
var c = ["0", "10", "2", "3"];

var delta = jsod.diff3(c, a, b, jsod.Presets.Configs.OrderedListDiffPure);
var merged = jsod.patchClone(a, delta);

console.log("a", a);
console.log("b", b);
console.log("c", c);
console.log("delta", delta);
console.log("merged", merged);
```

Leaves `merged` the same as `a`:

```
a [ '0', '1', '2', '3' ]
b [ '0', '1', '2', '3' ]
c [ '0', '10', '2', '3' ]
delta { '/': { '1': { '.': [Array] } } }
merged [ '0', '1', '2', '3' ]
```

If I change the inputs then I get the expected output:
```
a { foo: [ '0', '1', '2', '3' ] }
b { foo: [ '0', '10', '2', '3' ] }
c { foo: [ '0', '1', '2', '3' ] }
delta { '.': [ [ undefined, '~', [Object] ] ] }
merged { foo: [ '0', '10', '2', '3' ] }
```

But if I change `foo` in `b` and `c` then I get a conflict, while I would have expected both changes to be present in `merged`:

```
a { foo: [ '0', '1', '2', '3' ] }
b { foo: [ '0', '10', '2', '3' ] }
c { foo: [ '0', '1', '2', '30' ] }
delta { '!':
   [ { conflictType: 'CONFLICT_RECORD_DIFF_VALUE',
       A: [Array],
       B: [Array] } ] }
merged { foo: [ '0', '1', '2', '3' ] }
```

Are my expectations reasonable?

**Comment by Wortex17** [comment]
Sorry I didn't respond earlier, missed the notification.
I'll check this in the evening and come back to you on that

**Comment by Wortex17** [comment]
You're right on your first assumption, `merged` should be changes as youa ssume, even when enforcing handling the array as ordered using `OrderedListDiffPure`.
This is definitely a bug in the internal `addOrSetOrderListField` function which for some reason has slipped through my net.
I will be fixed ASAP.

On your second example, changing `foo` on `b` and `c` generating a conflict is indeed expected, if you use the `OrderedListDiffPure` preset.
This preset assumes that what you are feeding as an array-like ordered structure, not a full tree. So it sees the object with a member `foo`, but in both versions with different values: on the one hand there's `[ '0', '10', '2', '3' ]` and on the other `[ '0', '1', '2', '30' ]`. Both are arrays, treated as values. There is no recursion happening, because the containing object is already being treated as an ordered list of values.
Using the default preset (just omit the preset, use `null`or use `jsod.Presets.Configs.Default`) generates the results you expect.
